export const questions = [
  "Hva betyr egentlig ordet 'avocado' på aztekisk?",
  "Hvilket land har verdens korteste nasjonalsang?",
  "Hva kalles frykten for hull i ting?",
  "Hvilket dyr kan ikke se fargen rød?",
  "Hva var den første varen som ble solgt med strekkode?",
  "Hvilket land oppfant flamingo-dansen?",
  "Hva er det eneste dyret som ikke kan hoppe baklengs?",
  "Hvilket firma lagde den første computervirus?",
  "Hva betyr 'emoji' på japansk?",
  "Hvilket dyr har fingeravtrykk som er identiske med menneskers?",
  "Hva var opprinnelig brukt som betaling for de første pizzaene?",
  "Hvilket land har flest vulkaner per kvadratkilometer?",
  "Hva kalles studiet av ostesmaking?",
  "Hvilket dyr kan overleve i verdensrommet?",
  "Hva var den første McDonald's-burgeren som kostet over 1 dollar?",
  "Hvilket land oppfant sushi med laks?",
  "Hva er det eneste kontinentet uten edderkopper?",
  "Hvilket firma oppfant bubble wrap opprinnelig som tapet?",
  "Hva kalles frykten for klowns?",
  "Hvilket dyr har blått melk?",
  "Hva var Play-Doh opprinnelig laget for?",
  "Hvilket land har verdens lengste lunchpause?",
  "Hva er det eneste dyret som kan bli sjøsyk?",
  "Hvilket firma oppfant Post-it lapper ved et uhell?",
  "Hva betyr 'Coca-Cola' på kinesisk når det er dårlig oversatt?",
  "Hvilket land har flest tannleger per innbygger?",
  "Hva kalles frykten for å bli gravd ned levende?",
  "Hvilket dyr sover kun 2 timer per dag?",
  "Hva var den første filmen som ble vist på fly?",
  "Hvilket land oppfant karaoke?",
  "Hva er det eneste stedet på kroppen hvor hår vokser raskest?",
  "Hvilket dyr kan ikke brække seg?",
  "Hva var Viagra opprinnelig utviklet for å behandle?",
  "Hvilket land har verdens dyreste hamburgere?",
  "Hva kalles studiet av humør og latter?",
  "Hvilket dyr kan løpe på vann i 20 meter?",
  "Hva var den første drikken som ble solgt i boks?",
  "Hvilket land oppfant fortune cookies?",
  "Hva er det eneste dyret som kan få migrene?",
  "Hvilket firma oppfant den første smartwatch i 1972?",
  "Hva betyr 'spam' (søppelpost) opprinnelig?",
  "Hvilket land har verdens støyeste nasjonalsang?",
  "Hva kalles frykten for papir?",
  "Hvilket dyr kan ikke svette?",
  "Hva var den første varen som ble annonsert på TV?",
  "Hvilket land oppfant high-five?",
  "Hva er det eneste kontinentet hvor katter ikke eksisterer naturlig?",
  "Hvilket dyr kan huske ansikter i opptil 2 år?",
  "Hva var Nintendo opprinnelig et firma som solgte?",
  "Hvilket land har verdens dyreste toalettpapir?",
  "Hva kalles studiet av søppel og avfall?",
  "Hvilket dyr kan ikke se ned mens det flyr?",
  "Hva var den første filmen som brukte ordet 'damn'?",
  "Hvilket land oppfant yoghurt?",
  "Hva er det eneste dyret som kan få solbrenthet?",
  "Hvilket firma oppfant den første mobiltelefon som kunne ta bilder?",
  "Hva betyr 'Google' opprinnelig?",
  "Hvilket land har verdens mest besøkte museum?",
  "Hva kalles frykten for fremmede?",
  "Hvilket dyr kan endre kjønn når det trengs?",
  "Hva var den første dansen som ble forbudt av kirken?",
  "Hvilket land oppfant cornflakes for å forhindre noe spesielt?",
  "Hva er det eneste stedet på jorden hvor det aldri har regnet?",
  "Hvilket dyr kan ikke løpe og gå samtidig?",
  "Hva var den første byen som fikk trafikklys?",
  "Hvilket land har verdens lengste undergrunnsbane?",
  "Hva kalles studiet av flagg?",
  "Hvilket dyr kan sovne stående på ett ben?",
  "Hva var Nutella opprinnelig laget som erstatning for?",
  "Hvilket land oppfant sminke for menn først?",
  "Hva er det eneste kontinentet uten bier?",
  "Hvilket dyr kan ikke se sitt eget hode?",
  "Hva var den første boken som ble trykt med Gutenberg-pressen?",
  "Hvilket land har verdens høyeste skattetrykk på godteri?",
  "Hva kalles frykten for å bli sett på?",
  "Hvilket dyr kan løpe 50 km/t baklengs?",
  "Hva var den første drikken som ble kalt 'soft drink'?",
  "Hvilket land oppfant det moderne passystemet?",
  "Hva er det eneste dyret som kan le av vitser?",
  "Hvilket firma oppfant kredittkort ved et uhell?",
  "Hva betyr 'helicopter' bokstavelig talt på gresk?",
  "Hvilket land har verdens minste postkasse?",
  "Hva kalles studiet av navngiving?",
  "Hvilket dyr kan ikke lukke øynene?",
  "Hva var den første maten som ble mikrobølget?",
  "Hvilket land oppfant parkeringsbilletter?",
  "Hva er det eneste stedet på kroppen som ikke kan bli kald?",
  "Hvilket dyr kan ikke hoste?",
  "Hva var den første byen som fikk gatenavn?",
  "Hvilket land har verden lengste grense med seg selv?",
  "Hva kalles frykten for ord?",
  "Hvilket dyr kan ikke se bakover uten å snu hele kroppen?",
  "Hva var den første filmen som ble laget i farger?",
  "Hvilket land oppfant kaffe-til-go kopper?",
  "Hva er det eneste kontinentet hvor pingviner ikke lever naturlig?",
  "Hvilket dyr kan ikke løfte hodet over hjertet?",
  "Hva var Kleenex opprinnelig markedsført som?",
  "Hvilket land har verdens dyreste parkering?",
  "Hva kalles studiet av latter?",
  "Hvilket dyr kan ikke gå i ring?",
  "Hva var den første varen som ble solgt i vending machine?",
  "Hvilket land oppfant sugerør?",
  "Hva er det eneste dyret som kan få kvalme av å se på blod?",
  "Hvilket firma oppfant den elektriske tannarsten?",
  "Hva betyr 'barbecue' på det opprinnelige språket?",
  "Hvilket land har verdens korteste grense?",
  "Hva kalles frykten for matematikk?",
  "Hvilket dyr kan ikke puste gjennom munnen?",
  "Hva var den første byen som fikk fortau?",
  "Hvilket land oppfant glasskontakt-linser?",
  "Hva er det eneste kontinentet uten myrer?",
  "Hvilket dyr kan ikke svømme selv om det bor ved vann?",
  "Hva var Ketchup opprinnelig solgt som medisin for?",
  "Hvilket land har verdens dyreste bensin?",
  "Hva kalles studiet av drømmer?",
  "Hvilket dyr kan ikke se på dagtid?",
  "Hva var den første byen som fikk offentlig belysning?",
  "Hvilket land oppfant paraplyen?",
  "Hva er det eneste stedet på kroppen som aldri slutter å vokse?",
  "Hvilket dyr kan ikke spise og puste samtidig?",
  "Hva var den første drikken som ble servert kald på restaurant?",
  "Hvilket land har verdens raskeste internett?",
  "Hva kalles frykten for nye ting?",
  "Hvilket dyr kan ikke sove mer enn 5 minutter av gangen?",
  "Hva var den første filmen som vant Oscar?",
  "Hvilket land oppfant sjokolade-chip cookies ved et uhell?",
  "Hva er det eneste kontinentet uten krokodiller?",
  "Hvilket dyr kan ikke løpe ned en bakke?",
  "Hva var WD-40 opprinnelig utviklet for?",
  "Hvilket land har verdens laveste kriminalitet?",
  "Hva kalles studiet av humør?",
  "Hvilket dyr kan ikke hoppe i det hele tatt?",
  "Hva var den første byen som fikk rikstelefon?",
  "Hvilket land oppfant snus?",
  "Hva er det eneste dyret som kan snakke til seg selv?",
  "Hvilket firma oppfant den første laptopen?",
  "Hva betyr 'shampoo' på det opprinnelige språket?",
  "Hvilket land har verdens lengste broer?",
  "Hva kalles frykten for løgn?",
  "Hvilket dyr kan ikke åpne munnen under vann?",
  "Hva var den første restauranten som serverte iskrem?",
  "Hvilket land oppfant bowling?",
  "Hva er det eneste stedet på jorden hvor alle kart møtes?",
  "Hvilket dyr kan ikke lukke det ene øyet uten å lukke begge?",
  "Hva var Jell-O opprinnelig laget av?",
  "Hvilket land har verdens mest forurensede luft?",
  "Hva kalles studiet av lykke?",
  "Hvilket dyr kan ikke gåp?",
  "Hva var den første byen som fikk underjordisk kloakk?",
  "Hvilket land oppfant sykkel-taxi?",
  "Hva er det eneste kontinentet uten elver?",
  "Hvilket dyr kan ikke løpe og spise samtidig?",
  "Hva var Silly Putty opprinnelig utviklet som erstatning for?",
  "Hvilket land har verdens dyreste vann?",
  "Hva kalles frykten for musikk?",
  "Hvilket dyr kan ikke snu hodet 360 grader selv om folk tror det?",
  "Hva var den første filmen som hadde lydspor?",
  "Hvilket land oppfant frozen yogurt?",
  "Hva er den kjemiske formelen for vann?",
  "Hvilket firma oppfant den første e-posten?",
  "Hva betyr 'kangaroo' på det opprinnelige aboriginerspråket?",
  "Hvilket land har verdens tetteste befolkning?",
  "Hva kalles studiet av øl?",
  "Hvilket dyr kan ikke se under vann selv om det svømmer?",
  "Hva var den første byen som fikk elevator?",
  "Hvilket land oppfant rulletrapper?",
  "Hvor mange sider har en dodekagon?",
  "Hvilket dyr kan ikke puste hvis det legger seg på ryggen?",
  "Hva var Frisbee opprinnelig laget av?",
  "Hvilket land har verdens kaldeste postkontor?",
  "Hva kalles frykten for glass?",
  "Hvilket dyr kan ikke løpe i sirkler?",
  "Hva var den første drikken som ble solgt på flaske?",
  "Hvilket land oppfant tannkrem i tube?",
  "Hva er det største organet i kroppen?",
  "Hvilket dyr kan ikke se seg selv i speilet?",
  "Hva var cornstarch opprinnelig brukt til?",
  "Hvilket land har verdens mest besøkte tannlege?",
  "Hva kalles studiet av søvn?",
  "Hvilket dyr kan ikke hoppe over sin egen høyde?",
  "Hva var den første byen som fikk asfalterte veier?",
  "Hvilket land oppfant kaffebønne-kaffe?",
  "Hvilken planet er nærmest solen?",
  "Hvilket firma oppfant den første fjernkontrollen?",
  "Hva betyr 'hamburger' egentlig?",
  "Hvilket land har verdens høyeste fjell under vann?",
  "Hva kalles frykten for sykdom?",
  "Hvilket dyr kan ikke løpe oppover?",
  "Hva var den første byen som fikk offentlige toaletter?",
  "Hvilket land oppfant moderne tannbørste?",
  "Hvor mange vinger har en bie?",
  "Hvilket dyr kan ikke bite uten å åpne munnen helt?",
  "Hva var Lego opprinnelig et firma som laget?",
  "Hvilket land har verdens dyreste billetter til offentlig transport?",
  "Hva kalles studiet av farger?",
  "Hvilket dyr kan ikke se på nært hold?",
  "Hva var den første byen som fikk offentlig svømmebasseng?",
  "Hvilket land oppfant moderne solbriller?",
  "Hvor mange mager har en ku?",
  "Hvilket dyr kan ikke gå nedover trapper?",
  "Hva var Band-Aid opprinnelig laget for?",
  "Hvilket land har verdens lengste køer?",
  "Hva kalles frykten for hus?",
  "Hvilket dyr kan ikke sove i mørket?",
  "Hvor mange minutter er det i et døgn?",
  "Hvilket land har flest pizzarestauranter per innbygger?",
  "Hva var den første tegnefilmen som vant Oscar?",
  "Hvilket dyr kan bare se i svart-hvitt?",
  "Hva kalles frykten for å snakke i telefon?",
  "Hvilket land oppfant rullebrettet?",
  "Hvor mange timer sover en koala per dag?",
  "Hvilket dyr kan løpe raskest på kort distanse?",
  "Hva var den første bilen som hadde aircondition?",
  "Hvilket land har verdens dyreste internet?",
  "Hva kalles studiet av insekter?",
  "Hvilket dyr kan ikke åpne munnen under vann?",
  "Hva var den første byen som fikk pizza-levering?",
  "Hvilket land oppfant moderne sykkel?",
  "Hvilken farge blir du hvis du spiser for mange gulrøtter?",
  "Hvilket dyr kan ikke se rødt lys?",
  "Hva var den første sosiale medier-plattformen?",
  "Hvilket land har flest McDonald's per innbygger?",
  "Hva kalles frykten for bakterier?",
  "Hvilket dyr kan bare sove med halve hjernen av gangen?",
  "Hva var den første byen som fikk 24-timers butikker?",
  "Hvilket land oppfant moderne jeans?",
  "Hvor mange bein har en mygg?",
  "Hvilket dyr kan ikke hoppe selv om det har lange ben?",
  "Hva var den første filmen som brukte spesialeffekter?",
  "Hvilket land har verdens lengste navn?",
  "Hva kalles studiet av penger?",
  "Hvilket dyr kan ikke se farger i det hele tatt?",
  "Hva var den første byen som fikk WiFi gratis?",
  "Hvilket land oppfant moderne fotball?",
  "Hvilken øyenfarge er mest vanlig i verden?",
  "Hvilket dyr kan bare høre høye lyder?",
  "Hva var den første drikken som ble solgt på blikkboks?",
  "Hvilket land har flest biblioteker per innbygger?",
  "Hva kalles frykten for store folkemengder?",
  "Hvilket dyr kan ikke svømme selv om det bor i vann?",
  "Hva var den første byen som fikk gratis kollektivtransport?",
  "Hvilket land oppfant moderne snowboard?",
  "Hvor mange sekunder er det i en time?",
  "Hvilket dyr kan bare spise planter selv om det har tenner?",
  "Hva var den første TV-kanalen som sendte 24 timer i døgnet?",
  "Hvilket land har verdens høyeste bygning?",
  "Hva kalles studiet av stjerner?",
  "Hvilket dyr kan ikke se på nært hold?",
  "Hva var den første byen som fikk moderne helsevesen?",
  "Hvilket land oppfant moderne ski?",
  "Hvilken gass brukes mest i lysreklamer?",
  "Hvilket dyr kan bare leve i varmt vann?",
  "Hva var den første filmen som hadde undertekster?",
  "Hvilket land har flest kaffebarer per innbygger?",
  "Hva kalles frykten for høyder?",
  "Hvilket dyr kan ikke åpne øynene når det blir født?",
  "Hva var den første byen som fikk moderne brannvesen?",
  "Hvilket land oppfant moderne skateboard?",
  "Hva er det eneste dyret som kan få hjerteinfarkt av å bli redd?",
  "Hva er det eneste stedet på kroppen hvor du ikke kan få arr?",
  "Hva er det eneste kontinentet hvor det aldri snør?",
  "Hva er det eneste dyret som kan få depresjon?",
  "Hva er det eneste stedet på kroppen som regenererer seg hver 2. uke?",
  "Hva er det eneste kontinentet uten naturlig forekommende edelstener?",
];

export const correctAnswers = [
  "Testicle",
  "Japan",
  "Trypophobia",
  "Hund",
  "Tyggegummi",
  "Mexico",
  "Kenguru",
  "IBM",
  "Bildebilde",
  "Koala",
  "Fisk",
  "Island",
  "Casologie",
  "Tardigrad",
  "Quarter Pounder",
  "Norge",
  "Antarktis",
  "IBM",
  "Coulrofobi",
  "Hval",
  "Tapetrenser",
  "Spania",
  "Menneske",
  "3M",
  "Bit den vokshodet",
  "Norge",
  "Tafophobia",
  "Giraff",
  "Lost Horizon",
  "Japan",
  "Skjegg",
  "Hest",
  "Hjertesykdom",
  "Monaco",
  "Gelotologi",
  "Basilisk øgle",
  "Øl",
  "USA",
  "Menneske",
  "Seiko",
  "Spiced ham",
  "Montenegro",
  "Papyrophobia",
  "Gris",
  "Klokker",
  "USA",
  "Antarktis",
  "Sau",
  "Spillkort",
  "Japan",
  "Garbologi",
  "Pigeon",
  "Gone with the Wind",
  "Bulgaria",
  "Gris",
  "Sharp",
  "Feil på googol",
  "Frankrike",
  "Xenofobi",
  "Clownfisk",
  "Waltz",
  "USA",
  "Atacama ørkenen",
  "Hest",
  "Cleveland",
  "Kina",
  "Veksillologi",
  "Flamingo",
  "Sjokolade",
  "Egypt",
  "Antarktis",
  "Øgle",
  "Bibelen",
  "Danmark",
  "Scopophobia",
  "Struts",
  "Ginger ale",
  "Frankrike",
  "Menneske",
  "Diners Club",
  "Spiral wing",
  "San Marino",
  "Onomastikk",
  "Fisk",
  "Popcorn",
  "USA",
  "Tungen",
  "Hest",
  "Rom",
  "Canada",
  "Logophobia",
  "Ugle",
  "Snow White",
  "USA",
  "Afrika",
  "Giraff",
  "Gass-maske",
  "Monaco",
  "Gelotologi",
  "Elefant",
  "Tyggegummi",
  "USA",
  "Menneske",
  "General Electric",
  "Cooking meat",
  "Vatican",
  "Arithmophobia",
  "Hval",
  "Paris",
  "Tsjekkia",
  "Antarktis",
  "Øgle",
  "Mavesår",
  "Monaco",
  "Oneirologi",
  "Ugle",
  "Paris",
  "Egypt",
  "Negler",
  "Slange",
  "Øl",
  "Sør-Korea",
  "Neofobi",
  "Giraff",
  "Wings",
  "USA",
  "Europa",
  "Kenguru",
  "Rust prevention",
  "Island",
  "Humorologi",
  "Elefant",
  "New York",
  "Sverige",
  "Menneske",
  "IBM",
  "Massage head",
  "Kina",
  "Mythophobia",
  "Krokodille",
  "Frankrike",
  "Egypt",
  "Nordpolen",
  "Kenguru",
  "Kuhud",
  "India",
  "Eudemonologi",
  "Hest",
  "Rom",
  "Bangladesh",
  "Antarktis",
  "Gepard",
  "Gummi",
  "Japan",
  "Melophobia",
  "Ugle",
  "The Jazz Singer",
  "USA",
  "H2O",
  "ARPANET",
  "Jeg forstår ikke",
  "Monaco",
  "Zythologi",
  "Sel",
  "New York",
  "USA",
  "Tolv",
  "Gris",
  "Metall disk",
  "Antarktis",
  "Hyalophobia",
  "Kenguru",
  "Øl",
  "USA",
  "Huden",
  "Alle dyr",
  "Stivelse",
  "Japan",
  "Sømnologi",
  "Kenguru",
  "Rom",
  "Etiopia",
  "Merkur",
  "Zenith",
  "Fra Hamburg",
  "Japan",
  "Hypochondria",
  "Kenguru",
  "Paris",
  "Kina",
  "Fire",
  "Slange",
  "Leker",
  "Sveits",
  "Kromatologi",
  "Ørn",
  "Rom",
  "Italia",
  "Fire",
  "Kenguru",
  "Sårbeskyttelse",
  "India",
  "Domatophobia",
  "Katt",
  "1440",
  "USA",
  "Snow White",
  "Hund",
  "Telephonophobia",
  "USA",
  "20",
  "Gepard",
  "Packard",
  "Monaco",
  "Entomologi",
  "Krokodille",
  "New York",
  "Tyskland",
  "Oransje",
  "Hund",
  "Six Degrees",
  "USA",
  "Mysophobia",
  "Delfin",
  "Las Vegas",
  "USA",
  "Seks",
  "Giraff",
  "King Kong",
  "Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu",
  "Numismatikk",
  "Hund",
  "Seoul",
  "England",
  "Brun",
  "Elefant",
  "Øl",
  "Finland",
  "Agorafobi",
  "Flodhest",
  "Tallinn",
  "USA",
  "3600",
  "Panda",
  "CNN",
  "UAE",
  "Astronomi",
  "Ørn",
  "Paris",
  "Norge",
  "Neon",
  "Tropisk fisk",
  "The Jazz Singer",
  "Italia",
  "Akrofobi",
  "Katt",
  "London",
  "USA",
  "Hare",
  "Øynene",
  "Australia",
  "Menneske",
  "Hud",
  "Australia",
];

export const playerEmojis = [
  "🐸",
  "🦊",
  "🐻",
  "🐼",
  "🐨",
  "🦁",
  "🐯",
  "🐮",
  "🐷",
  "🐵",
  "🐶",
  "🐱",
  "🐭",
  "🐹",
  "🐰",
  "🦝",
  "🐺",
  "🐧",
  "🦅",
  "🦉",
  "🐙",
  "🦞",
  "🐢",
  "🦎",
  "🐍",
  "🐲",
  "🦄",
  "🐝",
  "🦋",
  "🌟",
  "⭐",
  "💫",
  "🔥",
  "❄️",
  "⚡",
  "🌈",
  "🍀",
  "🌺",
  "🌸",
];
