export const questions = [
  "What is the most stolen food item in the world?",
  "Which country has more time zones than any other?",
  "What percentage of the human brain is water?",
  "How many hearts does an octopus have?",
  "What is the fear of long words called?",
  "Which planet has the most moons in our solar system?",
  "What is the hardest natural substance on Earth?",
  "How many bones are babies born with?",
  "What is the smallest country in the world?",
  "Which blood type is known as the universal donor?",
  "What is the most abundant gas in Earth's atmosphere?",
  "How many chambers does a cow's stomach have?",
  "What is the loudest animal on Earth?",
  "Which mammal has no vocal cords?",
  "What percentage of Antarctica is covered by ice?",
  "How many teeth does an adult human typically have?",
  "What is the chemical symbol for gold?",
  "Which organ in the human body produces insulin?",
  "How many strings does a standard guitar have?",
  "What is the fastest land animal?",
  "Which element has the highest melting point?",
  "How many minutes are in a full day?",
  "What is the largest organ in the human body?",
  "Which gas makes up about 78% of Earth's atmosphere?",
  "How many legs does a lobster have?",
  "What is the smallest bone in the human body?",
  "Which planet is closest to the Sun?",
  "How many wings does a bee have?",
  "What is the most common eye color in humans?",
  "Which animal never sleeps?",
  "How many sides does a dodecagon have?",
  "What is the primary ingredient in glass?",
  "Which human organ can regenerate itself?",
  "How many chambers does a human heart have?",
  "What is the chemical formula for water?",
  "Which bird can fly backwards?",
  "How many ribs does a human have?",
  "What is the smallest unit of matter?",
  "Which metal is liquid at room temperature?",
  "How many years is a millennium?",
];

export const correctAnswers = [
  "Cheese",
  "France",
  "75%",
  "Three",
  "Hippopotomonstrosesquippedaliophobia",
  "Saturn",
  "Diamond",
  "270",
  "Vatican City",
  "O negative",
  "Nitrogen",
  "Four",
  "Blue whale",
  "Giraffe",
  "98%",
  "32",
  "Au",
  "Pancreas",
  "Six",
  "Cheetah",
  "Tungsten",
  "1440",
  "Skin",
  "Nitrogen",
  "Ten",
  "Stapes",
  "Mercury",
  "Four",
  "Brown",
  "Bullfrog",
  "Twelve",
  "Sand",
  "Liver",
  "Four",
  "H2O",
  "Hummingbird",
  "24",
  "Atom",
  "Mercury",
  "1000",
];
