// export const questions = [
//   "Hvilken mat blir stjålet mest i verden?",
//   "Hvilket land har flest tidssoner i verden?",
//   "Hvor mange prosent av hjernen består av vann?",
//   "Hvor mange hjerter har en blekksprut?",
//   "Hva kalles frykten for lange ord?",
//   "Hvilken planet har flest måner i solsystemet vårt?",
//   "Hva er det hardeste naturlige stoffet på jorden?",
//   "Hvor mange bein blir babyer født med?",
//   "Hva er det minste landet i verden?",
//   "Hvilken blodtype er kjent som universaldonor?",
//   "Hvilken gass utgjør mest av jordens atmosfære?",
//   "Hvor mange mager har en ku?",
//   "Hvilket dyr lager mest lyd i verden?",
//   "Hvilket pattedyr har ingen stemmebånd?",
//   "Hvor mange prosent av Antarktis er dekket av is?",
//   "Hvor mange tenner har en voksen person normalt?",
//   "Hva er det kjemiske symbolet for gull?",
//   "Hvilket organ i kroppen produserer insulin?",
//   "Hvor mange strenger har en vanlig gitar?",
//   "Hvilket dyr er raskest på land?",
//   "Hvilket grunnstoff har høyest smeltepunkt?",
//   "Hvor mange minutter er det i et døgn?",
//   "Hva er det største organet i kroppen?",
//   "Hvilken gass utgjør rundt 78% av jordens atmosfære?",
//   "Hvor mange ben har en hummer?",
//   "Hva er det minste beinet i kroppen?",
//   "Hvilken planet er nærmest solen?",
//   "Hvor mange vinger har en bie?",
//   "Hvilken øyenfarge er mest vanlig hos mennesker?",
//   "Hvilket dyr sover aldri?",
//   "Hvor mange sider har en dodekagon?",
//   "Hva er hovedingrediensen i glass?",
//   "Hvilket organ i kroppen kan regenerere seg selv?",
//   "Hvor mange kamre har et menneskehjerte?",
//   "Hva er den kjemiske formelen for vann?",
//   "Hvilken fugl kan fly baklengs?",
//   "Hvor mange ribben har et menneske?",
//   "Hva er den minste enheten av materie?",
//   "Hvilket metall er flytende ved romtemperatur?",
//   "Hvor mange år er et millennium?",
//   "Hvor mange øyne har en edderkopp?",
//   "Hvilken farge får urinen din hvis du spiser mye rødbeter?",
//   "Hvor mange fingre har Mickey Mouse?",
//   "Hvilken gas brukes mest i lysreklamer?",
//   "Hvor mange muskler bruker du for å smile?",
//   "Hvilket vitamin produserer kroppen når den eksponeres for sollys?",
//   "Hvor mange hjerneceller mister du hver dag?",
//   "Hvilken fugl kan ikke fly, men kan løpe opptil 50 km/t?",
//   "Hvor mange liter blod har en voksen person?",
//   "Hvilken sjømat kan leve i opptil 400 år?",
//   "Hvor mange prosent av kroppen består av vann?",
//   "Hvilket dyr har blått blod?",
//   "Hvor mange ganger blinker et menneske per dag?",
//   "Hvilken frukt har flest gener enn mennesker?",
//   "Hvor mange tenner har en hai?",
//   "Hvilket dyr kan ikke hoppe?",
//   "Hvor mange nyrer har et menneske normalt?",
//   "Hvilken planet roterer på siden?",
//   "Hvor mange kromosomer har et menneske?",
//   "Hvilket dyr har fingeravtrykk som ligner på menneskers?",
//   "Hvor mange liter luft puster et menneske inn hver dag?",
//   "Hvilken insekt kan løfte 50 ganger sin egen vekt?",
//   "Hvor mange bein har en mygg?",
//   "Hvilket dyr har den tykkeste huden?",
//   "Hvor mange sekunder er det i en time?",
//   "Hvilken fisk kan svømme baklengs?",
//   "Hvor mange ryggradsvirvler har en giraff?",
//   "Hvilket dyr har den lengste tungan i forhold til kroppsstørrelse?",
//   "Hvor mange liter spytt produserer et menneske per dag?",
//   "Hvilken planet har den korteste dagen?",
//   "Hvor mange hjerneslag har et menneske per minutt?",
//   "Hvilket dyr kan endre farge for å tilpasse seg omgivelsene?",
//   "Hvor mange kilometer er jordens omkrets ved ekvator?",
//   "Hvilken fugl legger de største eggene?",
//   "Hvor mange ledd har en regnorm?",
//   "Hvilket dyr har den høyeste temperaturen i kroppen?",
//   "Hvor mange liter oksygen produserer et tre per dag?",
//   "Hvilken planet er den kaldeste i solsystemet?",
//   "Hvor mange magnesiumatomer er det i klorofyll?",
//   "Hvilket dyr kan løpe på vannet?",
//   "Hvor mange prosent av hjernen bruker vi faktisk?",
//   "Hvilken fisk kan elektrosjokke med opptil 600 volt?",
//   "Hvor mange liter vann drikker en kamel på en gang?",
//   "Hvilket dyr har den beste hukommelsen?",
//   "Hvor mange hårstrå har et menneske på hodet?",
//   "Hvilken planet har den sterkeste tyngdekraften?",
//   "Hvor mange bakterier er det i munnen din?",
//   "Hvilket dyr kan sove stående?",
//   "Hvor mange kalorier brenner hjernen per dag?",
//   "Hvilken fugl kan dykke dypest under vann?",
//   "Hvor mange liter blod pumper hjertet per dag?",
//   "Hvilket dyr har den beste nattsyn?",
//   "Hvor mange ganger slår hjertet ditt per dag?",
//   "Hvilken planet har de sterkeste vindene?",
//   "Hvor mange smaksløker har tungen din?",
//   "Vilket dyr kan leve lengst uten vann?",
//   "Hvor mange DNA-baser har et menneske?",
//   "Hvilken fisk kan leve både i salt- og ferskvann?",
//   "Hvor mange millioner åndedrag tar et menneske i løpet av livet?",
//   "Hvilket dyr har den kraftigste kjeven?",
//   "Hvor mange meter høyt kan en kenguru hoppe?",
//   "Hvilken planet har den tynneste atmosfæren?",
//   "Hvor mange prosent av isen på jorden er i Antarktis?",
//   "Hvilket dyr kan regenerere hele lemmer?",
//   "Hvor mange liter vann trenger kroppen per dag?",
//   "Hvilken fugl kan fly høyest?",
//   "Hvor mange knoker har en slange?",
//   "Hvilket dyr har den raskeste stoffskiftet?",
//   "Hvor mange synapser har hjernen?",
//   "Hvilken planet har den lengste dagen?",
//   "Hvor mange liter luft er det i lungene dine?",
//   "Hvilket dyr kan løpe raskest i vann?",
//   "Hvor mange minutter kan hjernen overleve uten oksygen?",
//   "Hvilken fisk har den beste hukommelsen?",
//   "Hvor mange prosent av kroppen fornyes hver år?",
//   "Hvilket dyr har flest hjerneceller per gram hjerne?",
//   "Hvor mange meter kan en gepard springe på full fart?",
//   "Hvilken planet har den største månen?",
//   "Hvor mange elektriske impulser sender hjernen per sekund?",
//   "Hvilket land konsumerer mest kaffe per innbygger?",
//   "Hvor mange øyne har en kammskjell?",
//   "Hva er det mest giftige dyret i verden?",
//   "Hvilken farge har en polarbjørns hud?",
//   "Hvor mange hjerter har en regnorm?",
//   "Hvilket land oppfant is med pinne?",
//   "Hva er det eneste pattedyret som legger egg?",
//   "Hvor mange prosent av internettet er pornografi?",
//   "Hvilken fugl kan ikke gå baklengs?",
//   "Hva kalles studiet av flagg?",
//   "Hvor mange muskler har en elefants snabel?",
//   "Hvilket dyr har grønt blod?",
//   "Hva er det mest stjålne bibliotekboken i verden?",
//   "Hvor mange ganger blinker en giraff per time?",
//   "Hvilken frukt er teknisk sett en nøtt?",
//   "Hva er den vanligste fobien i verden?",
//   "Hvor mange liter spytt svelger du per dag?",
//   "Hvilket land har flest pyramider?",
//   "Hva er det eneste maten som aldri blir dårlig?",
//   "Hvor mange prosent av alle penger som noensinne er trykt ble trykt i 2020?",
//   "Hvilken by har flest broer i verden?",
//   "Hvor mange dager kan en skorpion overleve uten mat?",
//   "Hva er det dyreste krydderet i verden?",
//   "Hvilket dyr har flest mager?",
//   "Hvor mange timer sover en koala per dag?",
//   "Hvilken planet har den røde flekken?",
//   "Hva er det raskeste insektet i verden?",
//   "Hvor mange knokler har en nyfødt baby?",
//   "Hvilket metall brukes i termometere?",
//   "Hva er det lengste ordet i det norske språket?",
//   "Hvor mange liter melk produserer en ku per dag?",
//   "Hvilken fugl kan ikke snu hodet sitt?",
//   "Hva er det vanligste blodtypen i verden?",
//   "Hvor mange tenner har en krokodille?",
//   "Hvilket dyr kan løfte 10 ganger sin egen vekt?",
//   "Hva er det mest radioaktive elementet?",
//   "Hvor mange prosent av jorden er dekket av vann?",
//   "Hvilken fisk har ingen hjerne?",
//   "Hva er det mest solgte alkoholholdig drikken i verden?",
//   "Hvor mange ben har en edderkopp?",
//   "Hvilket dyr har den lengste svangerskapet?",
//   "Hva kalles frykten for klovner?",
//   "Hvor mange hjerter har en kråke?",
//   "Hvilken planet har ringer?",
//   "Hva er det eneste kontinentet uten ørkener?",
//   "Hvor mange meter lang er jordens lengste elv?",
//   "Hvilket dyr har den kraftigste biten?",
//   "Hva er det høyeste fjellet på Mars?",
//   "Hvor mange liter vann er det i Middelhavet?",
//   "Hvilken fugl kan ikke fly men kan løpe 70 km/t?",
//   "Hva er det vanligste grunnstoffet i universet?",
//   "Hvor mange øyer består Norge av?",
//   "Hvilket dyr kan leve lengst?",
//   "Hva er det høyeste bygget i verden?",
//   "Hvor mange prosent av kroppen er knokler?",
//   "Hvilken planet har den største stormen?",
//   "Hva er det minste landet i Afrika?",
//   "Hvor mange liter svette produserer kroppen per dag?",
//   "Hvilket dyr har den beste hørselen?",
//   "Hva er det dypeste punktet på jorden?",
//   "Hvor mange språk snakkes i Papua Ny-Guinea?",
//   "Hvilket dyr kan hoppe høyest?",
//   "Hva er det vanligste kjemiske elementet i jordens atmosfære?",
//   "Hvor mange centimeter vokser neglene per måned?",
//   "Hvilken by har flest innbyggere i verden?",
//   "Hva er det lengste tiernavnet på en fisk?",
//   "Hvor mange timer tar det jorden å rotere rundt sin egen akse?",
//   "Hvilket dyr har flest tennene?",
//   "Hva er det sterkeste materialet laget av mennesker?",
//   "Hvor mange knoker har en slange i ryggraden?",
//   "Hvilken fugl legger de minste eggene?",
//   "Hva er det vanligste metallet på jorden?",
//   "Hvor mange liter oksygen trenger et menneske per dag?",
//   "Hvilket dyr kan ikke svømme?",
//   "Hva er det mørkeste stedet på jorden?",
//   "Hvor mange måneder er det i en Merkur-dag?",
//   "Hvilket dyr har tre øyelokk?",
//   "Hva er det kaldeste stedet på jorden som er målt?",
//   "Hvor mange prosent av hjernen er aktiv når vi sover?",
//   "Hvilken fisk kan leve lengst ute av vann?",
//   "Hva er det største dyret som noensinne har levd?",
//   "Hvor mange liter luft puster en blåhval inn på et åndedrag?",
//   "Hvilket dyr har den tykkeste pelsen?",
//   "Hva er det mest brukte passordet i verden?",
//   "Hvor mange sekunder tar det lys å reise fra solen til jorden?",
//   "Hvilken fugl kan fly bakover og oppover?",
//   "Hva er det eneste stedet på kroppen som ikke har blodforsyning?",
//   "Hvor mange liter trykksaker bruker et menneske i løpet av livet?",
//   "Hvilket land har flest aktive vulkaner?",
//   "Hva er det vanligste fargeblindhet?",
//   "Hvor mange prosent av alle arter som noensinne har levd er nå utryddet?",
//   "Hvilket dyr har den kraftigste synet?",
//   "Hva er det mest brukte navnet i verden?",
//   "Hvor mange millioner bakterier er det på en mobiltelefon?",
//   "Hvilken planet har flest naturlige satellitter?",
//   "Hva er det eneste organet som kan flyte på vann?",
//   "Hvor mange år tar det Pluto å gå rundt solen?",
//   "Hvilket dyr produserer det sterkeste silket?",
//   "Hva er det tørreste stedet på jorden?",
//   "Hvor mange grader kan en ugle rotere hodet sitt?",
//   "Hvilken fisk kan elektrisk lade seg selv?",
//   "Hva er det vanligste kjønnsnavn i Norge?",
//   "Hvor mange prosent av alle diamanter brukes til smykker?",
//   "Hvilket dyr har den raskeste reaksjonstiden?",
//   "Hva er det største innsjøen i verden?",
//   "Hvor mange gram veier hjernen til et menneske?",
//   "Hvilken fugl kan dykke dypest i havet?",
//   "Hva er det sterkeste kjemiske syren?",
//   "Hvor mange liter væske består et menneske av?",
//   "Hvilket land har flest innsjøer i verden?",
//   "Hva er det vanligste elementet i menneskets kropp?",
//   "Hvor mange millimeter regn faller årlig i Sahara?",
//   "Hvilket dyr kan løpe oppover på vegger?",
//   "Hva er det lengste ordet i engelsk?",
//   "Hvor mange prosent av oksygenet på jorden produseres av havet?",
//   "Hvilken planet har den røde stormen?",
//   "Hva er det minste beinet i øret?",
//   "Hvor mange knoker har et menneske når det blir født?",
//   "Hvilket dyr har den lengste migrasjonen?",
//   "Hva er det eneste metallet som er flytende ved kroppstemperatur?",
//   "Hvor mange liter blod filtrerer nyrene per dag?",
//   "Hvilken fugl kan ikke lande på bakken?",
//   "Hva er det høyeste punktet på jorden?",
//   "Hvor mange prosent av jorden er ødeland?",
//   "Hvilket dyr kan ikke se farger?",
//   "Hva er det vanligste grunnstoffet i jordskorpen?",
//   "Hvor mange millioner nerveceller er det i hjernen?",
//   "Hvilken planet har den korteste dagen?",
//   "Hva er det eneste dyret som kan løpe på to ben?",
//   "Hvor mange liter tårer produserer øynene per dag?",
//   "Hvilket land har lengst kystlinje i verden?",
//   "Hva er det kraftigste magneten på jorden?",
//   "Hvor mange prosent av kroppen er muskler?",
//   "Hvilken fisk kan leve i både salt- og ferskvann?",
//   "Hva er det vanligste insektet på jorden?",
//   "Hvor mange kilometer per time beveger kontinentene seg?",
//   "Hvilket dyr har flest hjertekamre?",
//   "Hva er det sterkeste naturlige giftet?",
//   "Hvor mange liter luft inneholder lungene?",
//   "Hvilken fugl har den lengste vingespennvidden?",
//   "Hva er det mest solgte produktet i verden?",
//   "Hvor mange prosent av hjernen brukes til å se?",
//   "Hvilket dyr kan ikke bakke?",
//   "Hva er det eneste stedet hår ikke vokser på kroppen?",
//   "Hvor mange millioner sykluser per sekund kan hjernen prosessere?",
//   "Hvilken planet har den tykkeste atmosfæren?",
//   "Hva er det eneste kontinentet som ikke har maur?",
//   "Hvor mange liter saliva produserer munnen per dag?",
//   "Hvilket dyr har den beste luktesansen?",
//   "Hva er det lengste rivet på jorden?",
//   "Hvor mange prosent av alle fisk lever i ferskvann?",
//   "Hvilken fugl kan fly høyest i atmosfæren?",
//   "Hva er det vanligste allergenet i verden?",
//   "Hvor mange knokler er det i hånden?",
//   "Hvilket land har flest tidssoner totalt?",
//   "Hva er det eneste dyret som kan snakke som mennesker?",
//   "Hvor mange millioner celler dør i kroppen hver dag?",
//   "Hvilken planet har den kaldeste overflaten?",
//   "Hva er det eneste metallet som kan kuttes med kniv?",
//   "Hvor mange liter oksygen produseres av regnskogen per dag?",
//   "Hvilket dyr har den raskeste hjertefrekvensen?",
//   "Hva er det dypeste hullet boret av mennesker?",
//   "Hvor mange prosent av universet er mørk materie?",
//   "Hvilken fisk har ingen skjell?",
//   "Hva er det vanligste treet på jorden?",
//   "Hvor mange millioner arter finnes på jorden?",
//   "Hvilket dyr har den lengste levetiden?",
//   "Hva er det eneste organet som vokser hele livet?",
//   "Hvor mange liter væske filtreres av nyrene per time?",
//   "Hvilken fugl kan fly baklengs og sidelengs?",
//   "Hva er det mest radioaktive stedet på jorden?",
//   "Hvor mange prosent av jorden er dekket av skog?",
//   "Hvilket dyr kan ikke brække seg?",
//   "Hva er det lengste flyvende dyret?",
//   "Hvor mange millioner synapser dannes hver sekund hos babyer?",
//   "Hvilken planet har flest måner i solsystemet?",
//   "Hva er det eneste dyret som kan gråte tårer?",
//   "Hvor mange liter blod produserer kroppen per dag?",
//   "Hvilket land har størst andel ørken?",
//   "Hva er det kraftigste naturlige stoffet?",
//   "Hvor mange prosent av lufta vi puster ut er oksygen?",
//   "Hvilken fisk kan leve lengst?",
//   "Hva er det eneste kontinentet uten aktive vulkaner?",
//   "Hvor mange millioner bakterier er det per gram jord?",
//   "Hvilket dyr har flest gener?",
//   "Hva er det høyeste vannet på jorden?",
//   "Hvor mange liter vann bruker kroppen per dag til stoffskiftet?",
//   "Hvilken fugl kan ikke skille mellom farger?",
//   "Hva er det mest utbredte språket i verden?",
//   "Hvor mange prosent av hjernen er vann?",
//   "Hvilket dyr kan leve lengst uten å spise?",
//   "Hva er det eneste stedet på jorden uten bakterier?",
//   "Hvor mange millioner mennesker bor over 3000 meter over havet?",
//   "Hvilken planet har den varmeste kjernen?",
//   "Hva er det eneste dyret som kan løpe på tre ben?",
//   "Hvor mange liter luft puster et nyfødt barn per minutt?",
//   "Hvilket land har flest øyer i verden?",
//   "Hva er det kraftigste kjente magnetfeltet i universet?",
//   "Hvor mange prosent av kroppen er fett hos en sunn voksen?",
//   "Hvilken fisk kan hoppe høyest ut av vannet?",
//   "Hva er det eneste kontinentet som ikke har slanger?",
//   "Hvor mange millioner celler er det i menneskekroppen?",
//   "Hvilket dyr har den kraftigste luktesansen?",
//   "Hva er det lengste ordet som kan skrives med bare venstre hånd?",
//   "Hvor mange liter oksygen forbruker hjernen per dag?",
//   "Hvilken fugl har den beste hukommelsen?",
//   "Hva er det mest solgte boken i historien?",
//   "Hvor mange prosent av planeten er ubeboelig for mennesker?",
//   "Hvilket dyr kan endre kjønn?",
//   "Hva er det eneste stedet på kroppen som ikke har smertereceptorer?",
//   "Hvor mange millioner lightyear er det til nærmeste galakse?",
//   "Hvilken planet roterer raskest?",
//   "Hva er det eneste dyret som ikke kan få kreft?",
//   "Hvor mange liter væske er det i ryggrammen?",
//   "Hvilket land har den lengste grensen i verden?",
//   "Hva er det kraftigste naturlige eksplosive stoffet?",
//   "Hvor mange prosent av verdens ferskvann er tilgjengelig for drikking?",
//   "Hvilken fisk kan leve i -2 grader?",
//   "Hva er det eneste kontinentet som aldri har hatt krig?",
//   "Hvor mange millioner nevroner kobles sammen hver dag hos babyer?",
//   "Hvilket dyr har den tykkeste huden relativt til kroppsstørrelse?",
//   "Hva er det høyeste punktet på månen?",
//   "Hvor mange liter blod kan kroppen miste før den mister bevisstheten?",
//   "Hvilken fugl kan dykke dypest i is?",
//   "Hva er det mest kostbare metallet på jorden?",
//   "Hvor mange prosent av jordens overflate er fjell?",
//   "Hvilket dyr kan ikke puste og svelge samtidig?",
//   "Hva er det lengste flyet som noensinne er bygget?",
//   "Hvor mange millioner bakterier utveksles ved et kyss?",
//   "Hvilken planet har den sterkeste magnetiske feltet?",
//   "Hva er det eneste dyret som kan løpe på vannet uten å være liten?",
//   "Hvor mange liter luft inneholder brystkassen?",
//   "Hvilket land har flest språk som morsmål?",
//   "Hva er det kraftigste naturlige syren som finnes?",
//   "Hvor mange prosent av menneskene er venstrehendte?",
//   "Hvilken fisk kan leve på land i flere timer?",
//   "Hva er det eneste kontinentet som har pingviner naturlig?",
//   "Hvor mange millioner lysår er det til sentrum av galaksen vår?",
//   "Hvilket dyr har den beste fargesyn?",
//   "Hva er det lengste ordet som inneholder alle vokalene?",
//   "Hvor mange liter vann kan leveren rense per time?",
//   "Hvilken fugl kan ikke snu hodet sitt 180 grader?",
//   "Hva er det mest brukte ordet på alle språk?",
//   "Hvor mange prosent av hjernen består av fett?",
//   "Hvilket dyr kan leve i rommet?",
//   "Hva er det eneste stedet på jorden der det aldri regner?",
//   "Hvor mange millioner stjerner er det i Melkeveien?",
//   "Hvilken planet har den minste tyngdekraften?",
//   "Hva er det eneste dyret som kan smile ekte?",
//   "Hvor mange liter tårer gråter et menneske årlig?",
//   "Hvilket land har kortest gjennomsnittlig livslengde?",
//   "Hva er det kraftigste giftet produsert av mennesker?",
//   "Hvor mange prosent av kroppen fornyes hver sjunde år?",
//   "Hvilken fisk kan overleve i kokende vann?",
//   "Hva er det eneste kontinentet som har alle tidssoner?",
//   "Hvor mange millioner atomer er det i en celle?",
//   "Hvilket dyr har den raskeste verdensrekorden i løping?",
//   "Hva er det høyeste vannet som noensinne er målt?",
//   "Hvor mange liter oksygen kan lungene holde på maksimalt?",
//   "Hvilken fugl kan ikke lage lyd?",
//   "Hva er det mest solgte leketøyet i historien?",
//   "Hvor mange prosent av verden er dekket av ørkener?",
//   "Hvilket dyr kan ikke drømme?",
//   "Hva er det lengste ordet som kan leses likt forfra og bakfra?",
//   "Hvor mange millioner sandkorn er det på alle verdens strender?",
//   "Hvilken planet har den minste dagen?",
//   "Hva er det eneste dyret som kan telle til uendelig?",
//   "Hvor mange liter væske er det i øynene?",
//   "Hvilket land har den højeste gjennomsnittshøyden over havet?",
//   "Hva er det kraftigste eksplosive stoffet som finnes naturlig?",
//   "Hvor mange prosent av hjernen utvikles før 5-årsalderen?",
//   "Hvilken fisk kan leve i både varmt og kaldt vann?",
//   "Hva er det eneste kontinentet som ikke har naturlige bruer?",
//   "Hvor mange millioner celler skilles ut fra kroppen daglig?",
//   "Hvilket dyr har den tykkeste skallet?",
//   "Hva er det dypeste punktet i havet som mennesker har nådd?",
//   "Hvor mange liter blod kan hjertet pumpe per minutt maksimalt?",
//   "Hvilken fugl kan holde pusten lengst under vann?",
//   "Hva er det mest kostbare stoffet på jorden per gram?",
//   "Hvor mange prosent av jorden er flat nok til å bygge på?",
//   "Hvilket dyr kan ikke få solbrenthet?",
//   "Hva er det lengste ordet som ikke inneholder vokaler?",
//   "Hvor mange millioner lysimpulser sender øynene til hjernen per sekund?",
//   "Hvilken planet har den største månen relativt til sin egen størrelse?",
//   "Hva er det eneste dyret som kan synge i kor?",
//   "Hvor mange liter luft kan en toppidrettsutøver puste inn på et åndedrag?",
//   "Hvilket land har flest naturlige undergrunn?",
//   "Hva er det kraftigste naturlige antibiotika?",
//   "Hvor mange prosent av universet er vanlig materie?",
//   "Hvilken fisk kan leve på land i flere dager?",
//   "Hva er det eneste kontinentet som ikke har naturlige broer?",
//   "Hvor mange millioner bakterier er det på huden din?",
//   "Hvilket dyr har den beste evnen til å heale sår?",
//   "Hva er det høyeste punktet et menneske kan overleve uten oksygenmaske?",
//   "Hvor mange liter væske ligger rundt hjernen?",
//   "Hvilken fugl kan ikke fly med våte vinger?",
//   "Hva er det mest brukte ordet i alle bøker?",
//   "Hvor mange prosent av hjernen er aktiv når vi tenker hardt?",
//   "Hvilket dyr kan leve i minus 40 grader?",
//   "Hva er det eneste stedet på jorden som har magnetisk nordpol?",
//   "Hvor mange millioner sykluser kan hjertet slå maksimalt?",
//   "Hvilken planet har den tykkeste isskorpen?",
//   "Hva er det eneste dyret som kan få menneske-AIDS?",
//   "Hvor mange liter oksygen trenger hjernen per minutt?",
//   "Hvilket land har flest vulkaner per kvadratkilometer?",
//   "Hva er det kraftigste naturlige smertestillende stoffet?",
//   "Hvor mange prosent av alle levende organismer bor i havet?",
//   "Hvilken fisk kan overleve uten vann lengst?",
//   "Hva er det eneste kontinentet som har tre årstider?",
//   "Hvor mange millioner kilometer reiser jorden rundt solen per år?",
//   "Hvilket dyr har den beste evnen til regenerasjon?",
//   "Hva er det lengste ordet som kan skrives uten å løfte pennen?",
//   "Hvor mange liter væske er det mellom cellene i kroppen?",
//   "Hvilken fugl kan ikke stå på en fot?",
// ];
// export const correctAnswers = [
//   "Ost",
//   "Frankrike",
//   "75%",
//   "Tre",
//   "Hippopotomonstrosesquippedaliophobia",
//   "Saturn",
//   "Diamant",
//   "270",
//   "Vatikanstaten",
//   "O negativ",
//   "Nitrogen",
//   "Fire",
//   "Blåhval",
//   "Giraff",
//   "98%",
//   "32",
//   "Au",
//   "Bukspyttkjertelen",
//   "Seks",
//   "Gepard",
//   "Wolfram",
//   "1440",
//   "Huden",
//   "Nitrogen",
//   "Ti",
//   "Stigbøylen",
//   "Merkur",
//   "Fire",
//   "Brun",
//   "Delfin",
//   "Tolv",
//   "Sand",
//   "Leveren",
//   "Fire",
//   "H2O",
//   "Kolibri",
//   "24",
//   "Atom",
//   "Kvikksølv",
//   "1000",
//   "Åtte",
//   "Rosa",
//   "Fire",
//   "Neon",
//   "17",
//   "Vitamin D",
//   "100000",
//   "Struts",
//   "5-6",
//   "Grønlandshval",
//   "60%",
//   "Blekksprut",
//   "20000",
//   "Jordbær",
//   "40000",
//   "Elefant",
//   "To",
//   "Uranus",
//   "46",
//   "Koala",
//   "11000",
//   "Maur",
//   "Seks",
//   "Neshorn",
//   "3600",
//   "Ål",
//   "Syv",
//   "Kameleon",
//   "1.5",
//   "Jupiter",
//   "60-100",
//   "Kameleon",
//   "40075",
//   "Struts",
//   "150",
//   "Kolibri",
//   "20",
//   "Neptun",
//   "En",
//   "Basilisk øgle",
//   "100%",
//   "Elektrisk ål",
//   "200",
//   "Elefant",
//   "100000",
//   "Jupiter",
//   "1 milliard",
//   "Hest",
//   "400",
//   "Keiserpingvin",
//   "7000",
//   "Katt",
//   "100000",
//   "Neptun",
//   "10000",
//   "Kamel",
//   "3 milliarder",
//   "Laks",
//   "600 millioner",
//   "Krokodille",
//   "3",
//   "Mars",
//   "90%",
//   "Salamander",
//   "2-3",
//   "Gås",
//   "400",
//   "Spissmus",
//   "100 billioner",
//   "Venus",
//   "6",
//   "Delfin",
//   "4",
//   "Gullfisk",
//   "98%",
//   "Kolibri",
//   "500",
//   "Jupiter",
//   "1 million",
//   "Finland",
//   "200",
//   "Ferskvannsblekksprut",
//   "Svart",
//   "Fem",
//   "USA",
//   "Nebbdyr",
//   "37%",
//   "Flamingo",
//   "Veksillologi",
//   "40000",
//   "Skink",
//   "Guinness rekordbok",
//   "20",
//   "Jordbær",
//   "Araknofobi",
//   "1.5",
//   "Sudan",
//   "Honning",
//   "22%",
//   "Venezia",
//   "365",
//   "Safran",
//   "Drøvtygger",
//   "22",
//   "Jupiter",
//   "Øyenstikker",
//   "270",
//   "Kvikksølv",
//   "Minoritetsladningsbærerblokkeringsenhet",
//   "25",
//   "Ugle",
//   "O positiv",
//   "64",
//   "Gorilla",
//   "Polonium",
//   "71%",
//   "Manet",
//   "Øl",
//   "Åtte",
//   "Elefant",
//   "Coulrofobi",
//   "En",
//   "Saturn",
//   "Europa",
//   "6650",
//   "Saltvannskrokodille",
//   "Olympus Mons",
//   "4.2 millioner kubikkilometer",
//   "Emu",
//   "Hydrogen",
//   "150000",
//   "Grønlandshval",
//   "Burj Khalifa",
//   "15%",
//   "Jupiter",
//   "Seychellene",
//   "1",
//   "Elefant",
//   "Marianergropa",
//   "800",
//   "Puma",
//   "Nitrogen",
//   "0.3",
//   "Tokyo",
//   "Pneumonoultramicroscopicsilicovolcanokonios",
//   "24",
//   "Hai",
//   "Grafén",
//   "200-400",
//   "Kolibri",
//   "Jern",
//   "550",
//   "Sjimpanse",
//   "Marianergropa",
//   "2",
//   "Kamel",
//   "Antarktis",
//   "8.3",
//   "Kolibri",
//   "Blåhval",
//   "5000",
//   "Mus med sekk",
//   "123456",
//   "8",
//   "Kolibri",
//   "Hornhinnen",
//   "50000",
//   "Indonesia",
//   "Rød-grønn",
//   "99%",
//   "Ørn",
//   "Muhammad",
//   "25 millioner",
//   "Jupiter",
//   "Lungene",
//   "248",
//   "Edderkopp",
//   "Atacama ørkenen",
//   "270",
//   "Elektrisk ål",
//   "Ola",
//   "20%",
//   "Gepard",
//   "Kaspiske hav",
//   "1400",
//   "Keiserpingvin",
//   "Fluorsyre",
//   "42",
//   "Finland",
//   "Oksygen",
//   "25",
//   "Gekko",
//   "Pneumonoultramicroscopicsilicovolcanoconiosis",
//   "70%",
//   "Jupiter",
//   "Stigbøylen",
//   "270",
//   "Arktisk terne",
//   "Kvikksølv",
//   "180",
//   "Seiler",
//   "Mount Everest",
//   "33%",
//   "Hund",
//   "Oksygen",
//   "86 milliarder",
//   "Jupiter",
//   "Menneske",
//   "0.05",
//   "Canada",
//   "Neutrostjerne",
//   "40%",
//   "Laks",
//   "Maur",
//   "2.5",
//   "Blekksprut",
//   "Botulinum toksin",
//   "6",
//   "Albatross",
//   "Coca-Cola",
//   "25%",
//   "Elefant",
//   "Håndflaten",
//   "1000",
//   "Venus",
//   "Antarktis",
//   "1.5",
//   "Hund",
//   "Great Rift Valley",
//   "41%",
//   "Struts",
//   "Pollen",
//   "27",
//   "Russland",
//   "Papegøye",
//   "25 millioner",
//   "Pluto",
//   "Natrium",
//   "20 milliarder",
//   "Elefant",
//   "Kola Superdeep Borehole",
//   "27%",
//   "Ål",
//   "Gran",
//   "8.7 millioner",
//   "Grønlandshval",
//   "Nesen og ørene",
//   "7.5",
//   "Kolibri",
//   "Tsjernobyljsonen",
//   "31%",
//   "Hest",
//   "Pteranodon",
//   "1.8 millioner",
//   "Jupiter",
//   "Menneske",
//   "0.05",
//   "Libya",
//   "Diamant",
//   "16%",
//   "Grønlandshval",
//   "Australia",
//   "100 millioner",
//   "Paris japonicas",
//   "Angel Falls",
//   "1",
//   "Ugle",
//   "Mandarin",
//   "75%",
//   "Tardigrad",
//   "Steriliseringsrom",
//   "150 millioner",
//   "Jupiter",
//   "Kenguru",
//   "0.5",
//   "Finland",
//   "Magnetar",
//   "15-20%",
//   "Laks",
//   "Antarktis",
//   "37.2 billioner",
//   "Elefant",
//   "Sterilizers",
//   "3",
//   "Ravn",
//   "Bibelen",
//   "70%",
//   "Noen fiskearter",
//   "Hjernen",
//   "2.5 millioner",
//   "Jupiter",
//   "Hai",
//   "0.15",
//   "Russland",
//   "Nitroglyserin",
//   "0.3%",
//   "Arktisk fisk",
//   "Antarktis",
//   "2 millioner",
//   "Neshorn",
//   "Mons Huygens",
//   "1.5",
//   "Keiserpingvin",
//   "Rhodium",
//   "24%",
//   "Menneske",
//   "Boeing 747-8",
//   "80 millioner",
//   "Jupiter",
//   "Basilisk øgle",
//   "12",
//   "Papua Ny-Guinea",
//   "Fluorsyre",
//   "10%",
//   "Lungefisk",
//   "Antarktis",
//   "26000",
//   "Reke",
//   "Sequoia",
//   "55",
//   "Kolibri",
//   "Mama",
//   "60%",
//   "Tardigrad",
//   "Atacama ørkenen",
//   "400 milliard",
//   "Merkur",
//   "Menneske",
//   "50",
//   "Tsjaad",
//   "VX",
//   "90%",
//   "Laks",
//   "Asia",
//   "50 millioner",
//   "Salamander",
//   "Challenger Deep",
//   "30",
//   "Keiserpingvin",
//   "Antimaterie",
//   "30%",
//   "Hai",
//   "Krkkr",
//   "100 millioner",
//   "Pluto",
//   "Menneske",
//   "8",
//   "Bhutan",
//   "Penicillin",
//   "5%",
//   "Lungefisk",
//   "Antarktis",
//   "100 millioner",
//   "Elefant",
//   "Mount Everest",
//   "0.15",
//   "Ugle",
//   "The",
//   "100%",
//   "Tardigrad",
//   "Nordpolen",
//   "3 milliarder",
//   "Europa",
//   "Sjimpanse",
//   "0.5",
//   "Island",
//   "Morfin",
//   "99%",
//   "Lungefisk",
//   "Australia",
//   "940 millioner",
//   "Aksolotel",
//   "Sterilizers",
//   "35",
//   "Pingvin",
// ];
export const questions = [
  "Hvilken farge blir du hvis du spiser for mye gulrøtter?",
  "Hvor mange timer sover en katt per dag?",
  "Hvilken frukt er mest populær i verden?",
  "Hvor mange ben har en edderkopp?",
  "Hvilken dag i uka er det flest fødsler?",
  "Hvor mange grader kan en ugle snu hodet sitt?",
  "Hvilken pizza-topping er mest populær?",
  "Hvor mange øyne har en edderkopp?",
  "Hvilken farge har en giraff sin tunge?",
  "Hvor mange timer bruker nordmenn på mobilen per dag?",
  "Hvilken måned regner det mest i Norge?",
  "Hvor mange tenner har en hai?",
  "Hvilken iskremsmak er mest populær i Norge?",
  "Hvor mange muskler bruker du når du smiler?",
  "Hvilken dag spiser nordmenn mest pizza?",
  "Hvor mange liter vann skal du drikke per dag?",
  "Hvilken app brukes mest på telefonen?",
  "Hvor mange timer sover en teenager i gjennomsnitt?",
  "Hvilken farge får du hvis du blander rød og blå?",
  "Hvor mange prosent av kroppen er vann?",
  "Hvilken måned spiser vi mest is i Norge?",
  "Hvor mange øyer har Norge?",
  "Hvilken sport ser flest nordmenn på TV?",
  "Hvor mange km/t kan en gepard løpe?",
  "Hvilken streaming-tjeneste er størst i Norge?",
  "Hvor mange timer holder iPhone batteri i gjennomsnitt?",
  "Hvilken burger er mest populær på McDonald's?",
  "Hvor mange minutter tar det å koke et egg?",
  "Hvilken sosiale medier bruker norske ungdommer mest?",
  "Hvor mange timer står nordmenn opp om morgenen i helgen?",
  "Hvilken spillkonsoll selger best i Norge?",
  "Hvor mange prosent av nordmenn har Netflix?",
  "Hvilken bilmerke er mest populært i Norge?",
  "Hvor mange timer trener nordmenn per uke i gjennomsnitt?",
  "Hvilken godteri spiser nordmenn mest av?",
  "Hvor mange år lever en hund i gjennomsnitt?",
  "Hvilken kanal ser flest nordmenn på?",
  "Hvor mange kg sukker spiser en nordmann per år?",
  "Hvilken fast food-kjede har flest restauranter i Norge?",
  "Hvor mange timer per dag ser nordmenn på TV?",
  "Hvilken norsk artist har flest Spotify-streams?",
  "Hvor mange prosent av nordmenn kan svømme?",
  "Hvilken drikke drikker nordmenn mest av (utenom vann)?",
  "Hvor mange timer jobber nordmenn per uke i gjennomsnitt?",
  "Hvilken streaming-app brukes mest til musikk i Norge?",
  "Hvor mange ganger per år går nordmenn på kino?",
  "Hvilken type mat bestiller nordmenn mest hjem?",
  "Hvor mange prosent av nordmenn har førerkort?",
  "Hvilken aktivitet gjør norske familier mest sammen?",
  "Hvor mange timer per dag bruker nordmenn på sosiale medier?",
  "Hvilken norsk by har flest innbyggere?",
  "Hvor mange kopper kaffe drikker en nordmann per dag?",
  "Hvilken sport driver flest norske barn med?",
  "Hvor mange timer sover nordmenn i gjennomsnitt per natt?",
  "Hvilken norsk tradisjon er mest populær?",
  "Hvor mange prosent av nordmenn handler mat på nett?",
  "Hvilken type film ser nordmenn mest på?",
  "Hvor mange timer per uke gamer norske ungdommer?",
  "Hvilken transport bruker nordmenn mest til jobb?",
  "Hvor mange ganger per måned bestiller nordmenn takeaway?",
  "Hvilken hobby har flest nordmenn?",
  "Hvor mange språk snakker en nordmann i gjennomsnitt?",
  "Hvilken norsk fest feires mest?",
  "Hvor mange timer per dag lytter nordmenn til musikk?",
  "Hvilken type bok leser nordmenn mest?",
  "Hvor mange prosent av nordmenn bor i leilighet?",
  "Hvilken sosial aktivitet gjør nordmenn mest?",
  "Hvor mange timer per uke handler nordmenn?",
  "Hvilken teknologi bruker nordmenn mest hjemme?",
  "Hvor mange ganger per år reiser nordmenn utenlands?",
  "Hvilken norsk matvare eksporteres mest?",
  "Hvor mange timer per dag bruker barn på skjerm?",
  "Hvilken aktivitet liker norske pensjonister best?",
  "Hvor mange prosent av nordmenn trener regelmessig?",
  "Hvilken type musikk hører nordmenn mest på?",
  "Hvor mange timer per uke ser nordmenn på YouTube?",
  "Hvilken norsk tradisjon holder lengst?",
  "Hvor mange ganger per år går nordmenn til legen?",
  "Hvilken type klær kjøper nordmenn mest?",
  "Hvor mange timer per dag går nordmenn?",
  "Hvilken norsk by besøker flest turister?",
  "Hvor mange prosent av nordmenn er fornøyde med jobben sin?",
  "Hvilken type bøker låner nordmenn mest på biblioteket?",
  "Hvor mange timer per uke bruker nordmenn på husarbeid?",
  "Hvilken norsk tradisjonell rett lages mest hjemme?",
  "Hvor mange ganger per måned går nordmenn på restaurant?",
  "Hvilken type sport følger norske kvinner mest?",
  "Hvor mange timer sover norske barn i gjennomsnitt?",
  "Hvilken norsk naturopplevelse er mest populær?",
  "Hvor mange prosent av nordmenn har sommerhus?",
  "Hvilken type gave gir nordmenn mest til jul?",
  "Hvor mange timer per dag bruker nordmenn i trafikken?",
  "Hvilken norsk artist er mest populær blant ungdom?",
  "Hvor mange ganger per år bytter nordmenn mobiltelefon?",
  "Hvilken type mat lager nordmenn oftest til middag?",
  "Hvor mange timer per uke leser nordmenn bøker?",
  "Hvilken norsk idrettsstjerne er mest kjent?",
  "Hvor mange prosent av nordmenn bruker solkrem om sommeren?",
  "Hvilken type drikke kjøper nordmenn mest i butikken?",
  "Hvor mange timer per dag tilbringer nordmenn ute?",
  "Hvilken norsk film har flest sett?",
  "Hvor mange ganger per uke handler nordmenn dagligvarer?",
  "Hvilken type musikk danser nordmenn mest til?",
  "Hvor mange timer per natt våkner nordmenn i gjennomsnitt?",
  "Hvilken norsk tv-serie er mest populær?",
  "Hvor mange prosent av nordmenn har bikkje?",
  "Hvilken type øl drikker nordmenn mest?",
  "Hvor mange timer per dag bruker nordmenn på matlaging?",
  "Hvilken norsk høytid feires lengst?",
  "Hvor mange ganger per år går nordmenn til frisøren?",
  "Hvilken type sko bruker nordmenn mest om vinteren?",
  "Hvor mange timer per uke trener norske ungdommer?",
];

export const correctAnswers = [
  "Oransje",
  "12-16 timer",
  "Eple",
  "8",
  "Tirsdag",
  "270 grader",
  "Pepperoni",
  "8",
  "Blå",
  "3 timer",
  "Oktober",
  "300",
  "Vanilje",
  "17",
  "Fredag",
  "2 liter",
  "WhatsApp",
  "9 timer",
  "Lilla",
  "60%",
  "Juli",
  "50 000",
  "Fotball",
  "110 km/t",
  "Netflix",
  "12 timer",
  "Big Mac",
  "6 minutter",
  "Snapchat",
  "9:30",
  "PlayStation",
  "85%",
  "Tesla",
  "2 timer",
  "Sjokolade",
  "12 år",
  "NRK1",
  "35 kg",
  "McDonald's",
  "2.5 timer",
  "Karpe",
  "95%",
  "Kaffe",
  "37.5 timer",
  "Spotify",
  "3 ganger",
  "Pizza",
  "85%",
  "Se på TV",
  "2 timer",
  "Oslo",
  "3 kopper",
  "Fotball",
  "7.5 timer",
  "17. mai",
  "25%",
  "Komedie",
  "15 timer",
  "Bil",
  "3 ganger",
  "Gå tur",
  "2",
  "17. mai",
  "2 timer",
  "Krim",
  "45%",
  "Treffes venner",
  "3 timer",
  "Smartphone",
  "1.5 ganger",
  "Laks",
  "5 timer",
  "Lese bøker",
  "40%",
  "Pop",
  "8 timer",
  "Bunad",
  "4 ganger",
  "Jeans",
  "1 time",
  "Bergen",
  "75%",
  "Krim",
  "8 timer",
  "Fårikål",
  "2 ganger",
  "Fotball",
  "10 timer",
  "Nordlys",
  "30%",
  "Penger",
  "1 time",
  "Karpe",
  "2 år",
  "Pasta",
  "4 timer",
  "Bjørn Dæhlie",
  "60%",
  "Melk",
  "4 timer",
  "Kon-Tiki",
  "2 ganger",
  "Pop",
  "1 gang",
  "Skam",
  "35%",
  "Pilsner",
  "1 time",
  "Jul",
  "4 ganger",
  "Støvler",
  "6 timer",
];
export const playerEmojis = [
  "🐸",
  "🦊",
  "🐻",
  "🐼",
  "🐨",
  "🦁",
  "🐯",
  "🐮",
  "🐷",
  "🐸",
  "🐵",
  "🐶",
  "🐱",
  "🐭",
  "🐹",
  "🐰",
  "🦝",
  "🐺",
  "🐧",
  "🦅",
  "🦉",
  "🐙",
  "🦞",
  "🐢",
  "🦎",
  "🐍",
  "🐲",
  "🦄",
  "🐝",
  "🦋",
  "🌟",
  "⭐",
  "💫",
  "🔥",
  "❄️",
  "⚡",
  "🌈",
  "🍀",
  "🌺",
  "🌸",
];
